### ISSUE TITLE
This is a garbage extension. Not only does it not work but it broke all of my files turning them back to 4 tab rather than 2. After 8 hours of copy pasting, my ALT method won't even work because the TABS are broken. Stay away from this at all costs.

### ISSUE THREAD

**Issue by NullzInc** [axlan/vscode-multiline-find#1]

**Comment by axlan** [comment]
I'm sorry that occurred. It does seam like the "replace all" broke after some update (though I'm not really sure how your tabs were messed up). They also added a future that mostly deprecates this (in the file search menu) so I'm taking it off the store and leaving the code as reference.

**Comment by MartinFalatic** [comment]
Now I understand why this got pulled.

That's a shame, because while the _replace_ functionality may be broken (not a feature I used much if ever, personally), the _search_ functionality has been invaluable. When all you want to do is highlight a block and quickly see if that block is present elsewhere, it's worked great.

Try the same in VSCode and even with regex search off it insists on handling it as regex, which IMHO was a poor decision on their part (if I wanted regex matching I've have clicked the regex button... otherwise just take this multiline blob and match as-is).

Anyway, if you ever bring this back even with just the search capability, it'll come in handy. Meanwhile, I'll keep using the existing version.
